### PR TITLE
Backend rewrite

### PR DESCRIPTION
**Pull request by skrashevich**
The main backend functionality has been rewritten in Go. As a result, the entire application now weighs about 8MB and can be run either from a Docker container or as a single executable file.

Examples of compiled binaries, ready to run and weighing only ~5MB, can be found here: https://github.com/skrashevich/chatgpt-web/releases/tag/go-backend-nightly
Docker container: docker run -it --rm -p 3002:3002 -e OPENAI_API_KEY=$OPENAI_API_KEY skrashevich/chatgpt-web:go-backend (image size ~6MB)

### CODE REVIEW

**Comment by Chanzhaoyu** [comment]
Hey buddy, it looks really good. But me and my other maintainers are not familiar with Go

**Comment by liut** [comment]
Although I am a fan of the Go language, I strongly recommend that this Go implementation of the backend be put in a new project instead of being included in this project. If joint debugging is required, tools such as node-foreman, forego with Procfile support, or pm2 can be used.

虽然我是位Go粉，但我强烈建议，这个Go实现的后端放在放在一个新的项目中，而不要放在这个项目里，如果需要联合调试，可以尝试使用支持Procfile的node-foreman、forego等工具或者pm2也可以

**Comment by liut** [comment]
重新开了一个独立的后端项目，使用 Golang 实现 https://github.com/liut/morrigan，敬请关注

**Comment by Degree-21** [comment]
I checked the code and found that OPENAI was not used_ ACCESS_ TOKEN, is the ChatGPTUnificialProxy API request method missing

我查看了一下代码，发现并没有使用OPENAI_ACCESS_TOKEN，是否缺失 ChatGPTUnofficialProxyAPI 请求方式

**Pull request closed without merging**
